---
# tasks file for aa_system-configuration
- name: Ensure journald is configured
  become: true
  template:
   src: '{{ role_path }}/templates/etc/journald.conf.j2'
   dest: '/etc/systemd/journald.conf'
  notify: restart-systemd-journald

# http://bencane.com/2013/10/29/managing-dns-locally-with-etchosts/
- name: Ensure file content => /etc/hosts
  tags: [ sync, base ]
  blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('template', 'templates/etc/hosts.j2') }}"
    state: present